### ISSUE TITLE
Add support for alternate date encoding strategies in QueryDecoder.

### ISSUE THREAD

**Issue by dillan** [IBM-Swift/SafetyContracts#41]
Currently `QueryDecoder` only supports UTC dates formatted as `yyyy-MM-dd'T'HH:mm:ssZ`. It would be helpful for dates to be represented using alternate formats, such as `secondsSince1970`.

**Comment by ianpartridge** [comment]
Thanks for raising the issue :) We agree this is a current limitation and will take a look at how we can improve things. Thanks.

**Comment by dillan** [comment]
Thanks @ianpartridge. This is mostly to bring it up to parity with how alternate date formats may be used in other areas of Kitura.

**Comment by djones6** [comment]
This is now tagged in [KituraContracts 1.2.0](https://github.com/IBM-Swift/KituraContracts/releases/tag/1.2.0)

**Comment by djones6** [comment]
Update: for some reason this broke the Kitura tests.  I'm not sure how local testing failed to spot this.  I've deleted the 1.2.0 tag until I can figure this out.

Edit: the extension defining default values for the protocol additions was not declared public. #49 fixes this.  I'll re-tag 1.2.0 once this is merged.
