### ISSUE TITLE
UUID values should be usable as `Identifier`

### ISSUE THREAD

**Issue by mcritz** [IBM-Swift/SafetyContracts#46]
As a privacy-minded developer
I want UUID to be a supported Identifier type
To prevent disclosure of data 
Unlike today where  an easily determined pattern (such as incremented Int) can reveal approximate record lengths or other allow a curious user to scrape data from the API with ease.

**Comment by mcritz** [comment]
I plan on submitting my own PR with changes for this in the next couple days.

**Comment by djones6** [comment]
This is now tagged in `1.2.0`
